 name: CI/CD
 
 on:
   push:
     branches:
       - master
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
       - name: Login to DockerHub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Build and Push Docker Image
         run: |
           docker build -f cmd/server/Dockerfile -t anshad3808/cicd:latest .
           docker push anshad3808/cicd:latest
